FROM python:3.12-slim

RUN pip install --no-cache-dir \
  dagster \
  dagster-postgres \
  dagster-docker \
  "dlt[postgres]" \
  dbt-postgres \
  boto3 \
  httpx \
  openelectricity \
  xgboost \
  scikit-learn \
  mlflow \
  pandas \
  numpy \
  matplotlib \
  seaborn \
  joblib \
  psycopg2-binary \
  sqlalchemy \
  numpy

RUN mkdir -p /opt/dagster/app /opt/dagster/dlt /opt/dagster/dbt

WORKDIR /opt/dagster/app

EXPOSE 4000

CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "/opt/dagster/app/definitions.py"]
