FROM python:3.12-slim

RUN pip install --no-cache-dir \
    dagster \
    dagster-postgres

RUN mkdir -p /opt/dagster/app

WORKDIR /opt/dagster/app

EXPOSE 4000

HEALTHCHECK --timeout=1s --start-period=3s --interval=3s --retries=20 \
  CMD ["dagster", "api", "grpc-health-check", "-p", "4000"]

CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "/opt/dagster/app/definitions.py"]
