[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name            systemd
    Systemd_Filter  CONTAINER_NAME=electricity-dev_*
    Read_From_Tail  On
    Tag             container.*

[OUTPUT]
    Name         http
    Match        *
    Host         victorialogs
    Port         9428
    URI          /insert/jsonline
    Format       json_lines
    tls          Off
