[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         docker

[OUTPUT]
    Name         http
    Match        *
    Host         victorialogs
    Port         9428
    URI          /insert/jsonline
    Format       json_lines
    tls          Off
