# Stage 1: Bun base
FROM docker.io/oven/bun:1.3-alpine AS base
WORKDIR /app
COPY package.json ./
RUN bun install

FROM base AS development
COPY . .
RUN bun run dev --host

# Stage 3: Caddy serve
FROM docker.io/caddy:2-alpine
COPY --from=build-step /app/dist /usr/share/caddy
COPY Caddyfile /etc/caddy/Caddyfile
EXPOSE 80

# Stage 2: Build
FROM base AS build-step
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
COPY . .
RUN bun run build

