debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=${POSTGRES_USER:-postgres}
debezium.source.database.password=${POSTGRES_PASSWORD:-postgres}
debezium.source.database.dbname=electricity
debezium.source.topic.prefix=electricity
debezium.source.plugin.name=pgoutput
debezium.source.slot.name=debezium_silver_slot
debezium.source.publication.name=debezium_silver_pub
debezium.source.publication.autocreate.mode=filtered
debezium.source.table.include.list=silver.demand_5min

debezium.sink.type=nats-java
debezium.sink.nats.url=nats://nats:4222
debezium.sink.nats.subject=electricity.silver.demand_5min
