metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_secret = "a7952762c5dc44e455e24fd2c48c2cf629d0026ebe6cc35aff27e1355919c77a"

bootstrap_peers = []

[s3_api]
s3_region = "us-east-1"
api_bind_addr = "[::]:3900"

[s3_web]
bind_addr = "[::]:3903"
root_domain = ".web.garage.localhost"

[admin]
api_bind_addr = "0.0.0.0:3902"
admin_token = "changeme"
