FROM ghcr.io/mlflow/mlflow:v3.14.0

RUN pip install --no-cache-dir psycopg2-binary boto3

CMD mlflow server \
      --backend-store-uri "${MLFLOW_BACKEND_STORE_URI}" \
      --default-artifact-root "${MLFLOW_ARTIFACTS_DESTINATION}" \
      --serve-artifacts \
      --host 0.0.0.0 \
      --port 5000 \
      --allowed-hosts "*"
